services:
  postgres:
    image: postgres:latest
    env_file: .env.properties

  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env.properties
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      PHOTO_STORAGE_PATH: /data/photos
    volumes:
      - photos:/data/photos
    depends_on:
      - postgres

volumes:
  photos:
